Resources:

  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: EmployeeId
          AttributeType: S    
      KeySchema:
        - AttributeName: EmployeeId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 100
        WriteCapacityUnits: 100
      TableName: EmployeeTable
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: ServiceName
          Value: EmployeeService

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ProductId
          AttributeType: S    
      KeySchema:
        - AttributeName: ProductId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 100
        WriteCapacityUnits: 100
      TableName: ProductTable
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: ServiceName
          Value: ProductService

Outputs:

  EmployeeTableARN:
    Description: Link for Employee table
    Value: !GetAtt EmployeeTable.Arn

  ProductTableARN:
    Description: Link for Product table
    Value: !GetAtt ProductTable.Arn

  EmployeeTableStreamARN:
    Description: Link for Employee table stream
    Value: !GetAtt EmployeeTable.StreamArn

  ProductTableStreamARN:
    Description: Link for Product table stream
    Value: !GetAtt ProductTable.StreamArn




  

