Parameters:
  VPC:
    Description: VPC of the Load Balancer
    Type: AWS::EC2::VPC::Id
    Default: vpc-06b0228207c079e9f

  Subnets:
    Description: Public subnets for the load Balancer
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-0c1b6af8764756c2d,subnet-09816b4b52c9c191f

  SecurityGroup:
    Description: 'Security group for the load balancer'
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0c299d9331a4e08db

Resources:

  CCloudLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
      - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: ccloud-load-balancer

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CCloudLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup


  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP 

Outputs:
  CCloudLoadBalancer:
    Description: CCloud Load Balancer
    Value: !Ref CCloudLoadBalancer
  
  CCloudLoadBalancerUrl:
    Description: CCloud Load Balancer url
    Value: !GetAtt CCloudLoadBalancer.DNSName

  LoadBalancerListener:
    Description: HTTP listener of the load balancer
    Value: !Ref LoadBalancerListener
  
