Parameters:
  VPC:
    Description: VPC of the Load Balancer
    Type: AWS::EC2::VPC::Id
    Default: vpc-04fc12977a4628749

  Subnets:
    Description: Public subnets for the load Balancer
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-048bfab26ae9ba2d3,subnet-0288e772332b3c609

  SecurityGroup:
    Description: 'Security group for the load balancer'
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-037de1f4d71a34f53

Resources:

  CCloudLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
      - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: ccloud-load-balancer

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref CCloudLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultAction:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup


  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP 

Outputs:
  CCloudLoadBalancer:
    Description: CCloud Load Balancer
    Value: !Ref CCloudLoadBalancer
  
  LoadBalancerListener:
    Description: HTTP listener of the load balancer
    Value: !Ref LoadBalancerListener
  
