Parameters:
    VPCEndpointSubnet:
      Description: Subnet to place VPC endpoint
      Type: String

    SecurityGroup:
      Description: Security group for elasticsearch service
      Type: String

Resources:

  ElasticsearchService:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      EBSOptions:
        EBSEnabled: 'true'
        VolumeSize: 10
        VolumeType: standard
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t2.micro.elasticsearch
      ElasticsearchVersion: 2.3
      VPCOptions:
        SubnetIds:
          - !Ref VPCEndpointSubnet
        SecurityGroupIds:
          - !Ref SecurityGroup

Outputs:

  ElasticsearchServiceEndPoint:
    Value: !GetAtt ElasticsearchService.DomainEndpoint


    
    




