Parameters:
    VPCEndpointSubnet:
      Description: Subnet to place VPC endpoint
      Type: String

    SecurityGroup:
      Description: Security group for elasticsearch service
      Type: String

Resources:
  ElasticsearchService:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: ccloud
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principle:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/ccloud/*
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      EBSOptions:
        EBSEnabled: 'true'
        VolumeSize: 10
        VolumeType: standard
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t2.micro.elasticsearch
      ElasticsearchVersion: 2.3
      VPCOptions:
        SubnetIds:
          - !Ref VPCEndpointSubnet
        SecurityGroupIds:
          - !Ref SecurityGroup

Outputs:

  ElasticsearchServiceEndPoint:
    Value: !GetAtt ElasticsearchService.DomainEndpoint


    
    




