Parameters:

  VPCCIDRBlock:
    Description: CIDR Block for the VPC
    Type: String
    Default: 172.33.0.0/16

  PublicSubnet1Block:
    Description: CIDR Block for first public subnet
    Type: String
    Default: 172.33.1.0/24

  PublicSubnet2Block:
    Description: CIDR Block for second public subnet
    Type: String
    Default: 172.33.2.0/24

  PrivateSubnet1Block:
    Description: CIDR Block for first private subnet
    Type: String
    Default: 172.33.3.0/24

  PrivateSubnet2Block:
    Description: CIDR Block for second private subnet
    Type: String
    Default: 172.33.4.0/24

Resources:
  
  # VPC
  CCloudVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDRBlock
      Tags:
        - Key: Name
          Value: ccloud-vpc 
      
  # Public subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CCloudVPC
      AvailabilityZone: !Select [0,!GetAZs ""]
      CidrBlock: !Ref PublicSubnet1Block
      Tags:
        - Key: Name
          Value: ccloud-public-sub-net-1
      

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:  
      VpcId: !Ref CCloudVPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref PublicSubnet2Block
      Tags:
        - Key: Name
          Value: ccloud-public-sub-net-2

  # Private subnets   
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CCloudVPC
      AvailabilityZone: !Select [0,!GetAZs ""]
      CidrBlock: !Ref PrivateSubnet1Block
      Tags:
        - Key: Name
          Value: ccloud-private-sub-net-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CCloudVPC
      AvailabilityZone: !Select [1,!GetAZs ""]
      CidrBlock: !Ref PrivateSubnet2Block
      Tags:
        - Key: Name
          Value: ccloud-private-sub-net-2
  
  # Internet Gateway
  CCloudInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ccloud-internet-gateway

  # Attaching internet gateway to the VPC
  InternetGatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref CCloudInternetGateway
      VpcId: !Ref CCloudVPC