Parameters:

  DockerImage:
    Description: Docker Image for the products service
    Type: String
    Default: namila/ccloud-products-service:latest

  VPC:
    Description: VPC for the service
    Type: AWS::EC2::VPC::Id

  Cluster: 
    Description: Cluster for the service
    Type: String
  
  Replication:
    Description: Desired count of the service
    Type: Number
    Default: 2

  MaxReplication:
    Description: Maximum replication
    Type: Number
    Default: 10

  LoadBalancerListener:
    Description: Load balancer listener
    Type: String
  
  ServicePath:
    Description: service uri
    Type: String
    Default: /products

  HealthCheckPath:
    Description: health check uri
    Type: String
    Default: /health

  ContainerPort:
    Description: port exposed by the container
    Type: Number
    Default: 3000

  ServiceAutoScalingRoleARN:
    Description: Service autoscalling roll ARN
    Type: String
  
  ElasticSearchDomain:
    Description: Elasticsearch domain
    Type: String

Resources:

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      ListenerArn: !Ref LoadBalancerListener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref ServicePath
      Actions:
        - TargetGroupArn: !Ref LoadBalancerTargetGroup
          Type: forward

  LoadBalancerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub load-balancer-service-role-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
          "Statement": [{
            "Effect": "Allow",
            "Principal": {"Service": [ "ecs.amazonaws.com" ]},
            "Action": [ "sts:AssumeRole" ]
          }]
        }
      Policies:
        - PolicyName: ccloud-load-balancer-policy
          PolicyDocument: |
            {
              "Statement": [{
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*"
              }]
            }

  ProductsServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 365

  ProductsServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ccloud-products-service
      ContainerDefinitions:
        - Name: ccloud-products-app
          Essential: true
          Image: !Ref DockerImage
          Memory: 128
          Environment:
            - Name: ElasticSearchDomain
              Value: !Ref ElasticSearchDomain
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ProductsServiceLogGroup
              awslogs-region: !Ref AWS::Region 


  CCloudProductsService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListenerRule
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref LoadBalancerServiceRole
      DesiredCount: !Ref Replication
      TaskDefinition: !Ref ProductsServiceTaskDefinition
      LoadBalancers:
        - ContainerName: ccloud-products-app
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref LoadBalancerTargetGroup


  CCloudProductServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxReplication
      MinCapacity: !Ref Replication
      ResourceId: !Join
        - /
        - - service
          - !Ref Cluster
          - !GetAtt CCloudProductsService.Name
      RoleARN: !Ref ServiceAutoScalingRoleARN
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  CCloudProductServiceScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CCloudProductServiceScaleOutPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref CCloudProductServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 1

  CCloudProductServiceMemoryScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Memory Utilization more than 60 percentage products service
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref Cluster
        - Name: ServiceName
          Value: !GetAtt CCloudProductsService.Name
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref CCloudProductServiceScaleOutPolicy


  CCloudProductServiceScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CCloudProductServiceScaleInPolicy
      PolicyType: StepScaling
      ScalingTargetId: !Ref CCloudProductServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1

  CCloudProductsServiceMemoryScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Memory Utilization less than 60 percentage products service
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref Cluster
        - Name: ServiceName
          Value: !GetAtt CCloudProductsService.Name
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 60
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref CCloudProductServiceScaleInPolicy



