Parameters:
  ElasticSearchSubnet:
    Description: Subnet of the elasticsearch service
    Type: String

  SecurityGroup:
    Description: Security group for elasticsearch service
    Type: String


Resources:
  CCloudIndexer:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ccloudIndexer
      Runtime: nodejs
      Code: ''
      Handler: ''
      Role: ''
      VpcConfig:
        SecurityGroupIds:
          - !Ref 
        SubnetId:
          -

